# -*- coding: utf-8 -*-
"""Unemployment Analysis With Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEOF85yZmzZNix4sS-SR1fOyfcxHDpSA
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_csv("Unemployment in India.csv")

df.head()

df.describe()

df.info()

df.isnull().sum()

print("Shape before cleaning Non values:",df.shape)

df1=df.dropna()

print("Shape after removing Nan values:",df1.shape)

df.head()

df1.columns

df.info()

print("Grouping Unemployment Data by :",df1.groupby("Region").size())

x=df1["Region"]  #Assigning 'region' column to variable "x"

y=df1[" Estimated Unemployment Rate (%)"] #Assigning 'Estimated Unemployment Rate (%) to (y)

x  #Displaying x

y #Displaying y

plt.figure(figsize=(15,10))
sns.countplot(x="Region",data=df1)
plt.xticks(rotation=45)
plt.ylabel("Estimated unemployment rate(%)")

print(df1)  #Printing df1